GRLIB = C:\Users\Admin\Downloads\Programs\ReadyLib\dev
GSRC = ..\code\GProject\src
GBIN = bin
GBUILD = build
GTARGET = $(GBIN)\gp_cpp.exe

GINCS = \
    -I$(GSRC)\include \
    -I$(GRLIB)\exprtk\mingw\include \
    -I$(GRLIB)\muparser\mingw\include \
    -I$(GRLIB)\gsl\mingw\include \
    -I$(GRLIB)\opencv\mingw\include \
    -I$(GRLIB)\cmocka\1.1.0\mingw32\include \

GLIBS = \
    -L$(GRLIB)\muparser\mingw\lib \
    -L$(GRLIB)\cmocka\1.1.0\mingw32\lib \
    $(GRLIB)\cmocka\1.1.0\mingw32\lib\libcmocka.dll.a \
    -lmuparser \
    -lcmocka \
    
GOBJS = \
    $(patsubst $(GSRC)/%.cpp, $(GBUILD)/%.o, $(wildcard $(GSRC)/*.cpp)) \
    $(patsubst $(GSRC)/manager/%.cpp, $(GBUILD)/%.o, $(wildcard $(GSRC)/manager/*.cpp)) \

GCFLAGS = \
    -std=gnu++11 \
    #-Wl,--wrap \
    #-Wa,-mbig-obj \
    
all: compile run

compile: $(GOBJS)
	@if not exist $(GBIN) ( mkdir $(GBIN) )
	g++ $(GCFLAGS) -o $(GTARGET) $(GOBJS) $(GLIBS) 
$(GBUILD)/%.o: $(GSRC)/%.cpp
	@if not exist $(GBUILD) ( mkdir $(GBUILD) )
	g++ $(GCFLAGS) -c $< -o $@ $(GINCS)
$(GBUILD)/%.o: $(GSRC)/manager/%.cpp
	@if not exist $(GBUILD) ( mkdir $(GBUILD) )
	g++ $(GCFLAGS) -c $< -o $@ $(GINCS)
qmake:
	@qmake
run:
	@$(GTARGET)
clean: 
	del /q $(GBUILD)\*.* $(GTARGET)
