GBIN = bin
GBUILD = build
GTARGET = $(GBIN)/gp_cpp
GRES = resources.qrc

all: clean_exe qmake compile run

qmake:
	@qmake
compile:
	@make
run:
	@$(GTARGET)
clean_exe: 
	rm -f $(GBIN)/*
clean: 
	make clean
	rm -f $(GBUILD)/* $(GBIN)/*
