GSRC = ../code/GProject/src
GBIN = bin
GBUILD = build
GTARGET = $(GBIN)/gp_cpp.exe

GINCS = \
    -I$(GSRC)/include \
    -IC:\Users\Admin\Downloads\Programs\ReadyLib\dev\muparser\win\include \

GLIBS = \
    C:\Users\Admin\Downloads\Programs\ReadyLib\dev\muparser\win\lib\libmuparser.a \
    
GOBJS = \
    $(patsubst $(GSRC)/%.cpp, $(GBUILD)/%.o, $(wildcard $(GSRC)/*.cpp)) \
    $(patsubst $(GSRC)/manager/%.cpp, $(GBUILD)/%.o, $(wildcard $(GSRC)/manager/*.cpp)) \

GCFLAGS = \
    -std=c++17 \
    
all: compile run

compile: $(GOBJS)
	g++ -o $(GTARGET) $(GOBJS) $(GLIBS) 
$(GBUILD)/%.o: $(GSRC)/%.cpp
	g++ $(GCFLAGS) -c $< -o $@ $(GINCS)
$(GBUILD)/%.o: $(GSRC)/manager/%.cpp
	g++ $(GCFLAGS) -c $< -o $@ $(GINCS)
qmake:
	@qmake
run:
	@$(GTARGET)
clean: 
	rm -f $(GBUILD)/*.o $(GBIN)/*.exe
