GSRC = ../code/GProject/src
GBIN = bin
GBUILD = build
GTARGET = $(GBIN)/gp_cpp.exe

GINCS = \
    -I$(GSRC)/include \

GLIBS = \

GOBJS = \
    $(patsubst $(GSRC)/%.cpp, $(GBUILD)/%.o, $(wildcard $(GSRC)/*.cpp)) \
    $(patsubst $(GSRC)/manager/%.cpp, $(GBUILD)/%.o, $(wildcard $(GSRC)/manager/*.cpp))

GCFLAGS = \

all: compile run

compile: $(GOBJS)
	@if ! [ -d "$(GBIN)" ] ; then mkdir $(GBIN) ; fi
	g++ -o $(GTARGET) $(GOBJS) $(GLIBS) 
$(GBUILD)/%.o: $(GSRC)/%.cpp
	@if ! [ -d "$(GBUILD)" ] ; then mkdir $(GBUILD) ; fi
	g++ $(GCFLAGS) -c $< -o $@ $(GINCS)
$(GBUILD)/%.o: $(GSRC)/manager/%.cpp
	@if ! [ -d "$(GBUILD)" ] ; then mkdir $(GBUILD) ; fi
	g++ $(GCFLAGS) -c $< -o $@ $(GINCS)
qmake:
	@qmake
run:
	@$(GTARGET)
clean: 
	rm -f $(GBUILD)/*.o $(GBIN)/*.exe
